### ISSUE TITLE
Add option to "buy" upgrade in the planner

### ISSUE THREAD

**Issue by jab416171** [DenysAshikhin/gameplay-planner#13]
If you have the planner open and the game open, and an upgrade becomes affordable, like residue or protein or infinity corner, adding the option to click "buy" in the planner to simulate buying it, then updating everything else as if it was purchased in the save, avoids having to save the game and re-import the save. On the next import these temporary "buys" should probably be erased to avoid any desync.

**Comment by MeLovesCheese** [comment]
Would it be possible to have an option to keep the purchased reincarnation exp levels? It might be nice for quality of life because if we are purposly ignoring reincarnation exp levels then we need to click through future purchases until reincarnation exp is no longer the only upgrade that appears in the list. I currently need to click a 15-16 times to see that it finally wants other upgrades

**Comment by DenysAshikhin** [comment]
> If you have the planner open and the game open, and an upgrade becomes affordable, like residue or protein or infinity corner, adding the option to click "buy" in the planner to simulate buying it, then updating everything else as if it was purchased in the save, avoids having to save the game and re-import the save. On the next import these temporary "buys" should probably be erased to avoid any desync.

This probably won't ever just because I'd need to figure out a consistent way to keep track of all of that in the background accurately. And even then, that assumes linear progression which will be wrong. I've tried this with farming and it's just way to hard to pin down

**Comment by DenysAshikhin** [comment]
> Would it be possible to have an option to keep the purchased reincarnation exp levels? It might be nice for quality of life because if we are purposly ignoring reincarnation exp levels then we need to click through future purchases until reincarnation exp is no longer the only upgrade that appears in the list. I currently need click 15-16 times to see that it finally wants other upgrades

You prob won't like me, but if this is about reinc upgrade from residue, there will no longer be a buy option (or a future option). It will be like the IC page, but I'll keep the side list of what to buy. It will only go as far as you can afford. And after you'll have to come back to it... otherwise its again maybe nice to know what comes up, but the planner won't know exactly how far to predict for you.

**Comment by DenysAshikhin** [comment]
If there's no other input I'll close this in a few weeks~

**Comment by jab416171** [comment]
> This probably won't ever just because I'd need to figure out a consistent way to keep track of all of that in the background accurately. And even then, that assumes linear progression which will be wrong. I've tried this with farming and it's just way to hard to pin down
How does this assume linear progression? Let's try an example.
You're on the residue screen, and it says to buy 1 attack upgrade. So you buy it in game, you click buy in the planner, that available upgrade goes away, and it shows you the next upgrade you should buy.
Similar with protein, the planner says to buy #10, so you buy it, then it goes away, and all of the other ones adjust in time left and cost etc.

**Comment by DenysAshikhin** [comment]
> > This probably won't ever just because I'd need to figure out a consistent way to keep track of all of that in the background accurately. And even then, that assumes linear progression which will be wrong. I've tried this with farming and it's just way to hard to pin down
> 
> How does this assume linear progression? Let's try an example. You're on the residue screen, and it says to buy 1 attack upgrade. So you buy it in game, you click buy in the planner, that available upgrade goes away, and it shows you the next upgrade you should buy. Similar with protein, the planner says to buy #10, so you buy it, then it goes away, and all of the other ones adjust in time left and cost etc.

OH I see, I misunderstood as you want the planner to keep track of elapsed time (say every minute) and see if you can afford to buy a new purchase

**Comment by DenysAshikhin** [comment]
If its more just to be able to mark a suggestion as purchased, that's better. The issue there is only if you want it to show future upgrades (i.e.) ones you can't afford, that I'll probably not grapple with until all other things are resolved/fixed. But just showing the remaining suggested purchases, this is more feasible in the future (if I understood correctly this time)

**Comment by jab416171** [comment]
You already have future purchase order for residue, and the accept button. this would be applying similar logic to the reincarnation points and the protein pages.

**Comment by DenysAshikhin** [comment]
While I technically have it right now, I will be reworking that because there are a bunch of issues with it - so I won't technically have it going forward. I also want to simplify the pages overall and getting rid of extra buttons that aren't (IMO) critical/add massive qol/functionality is the best way. And another reason why I don't want to recreate this functionality after reworking the residue logic behind the scenes.

If there's a point I'm missing other than a bit of qol for clicking accept a bunch to see future orders (ones you can't currently afford) let me know and I'll reconsider for sure

**Comment by DenysAshikhin** [comment]
Haven't seen any activity here so will be closing for now
