### ISSUE TITLE
Because of promotions very important "ignore pet rank" button missing in pet team tab!

### ISSUE THREAD

**Issue by Treboras** [DenysAshikhin/gameplay-planner#32]
As the title suggests: The Pet Team tab should have an "ignore pet rank" option **ASAP**!

Max 10/10 Promotion pets are ignored because of low expedition rank in spite of them being the very best option for the team after they have been leveld/ranked up a bit.

Otherwise this completely negates the massive benefit of maxing early pets cheaply.

Thanks!

**Comment by DenysAshikhin** [comment]
Closing this out as this isn't true (if you have a concrete example + case feel free to re-open). I believe we worked together and I added an experimental feature for a bit to equalise pets. But, it didn't really help much in the end. if you want 10/10 pets to be recommended, turn off `max top stat`. If they have good stat lines and promos they will be recommended over worse pets.

This is because without max top stat, it doesn't care about levels/ranks but only the score of a pet. Score is determined by how well the stat lines match your priority list and receive a boost from each promo level
